# Generated by Django 5.1.3 on 2024-11-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_restaurant_coords_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Entradas', 'Entradas'), ('PlatosPrincipales', 'Platos Principales'), ('Postres', 'Postres')], max_length=50),
        ),
    ]
