# Generated by Django 5.1.3 on 2024-11-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_review_comida_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='abundancia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='ambiente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='atencion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='calidadPrecio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='limpieza',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='sabor',
            field=models.FloatField(default=0.0),
        ),
    ]
